apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kicker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-kicker-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-kicker-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-kicker-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-kicker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-kicker
  labels:
    app: pod-kicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-kicker
  template:
    metadata:
      labels:
        app: pod-kicker
    spec:
      serviceAccountName: pod-kicker-sa
      containers:
      - name: pod-kicker
        image: hauro/pod-kicker:latest
        ports:
        - containerPort: 8450
        env:
        - name: REPO_URL
          value: "https://hub.docker.com/r/jellyfin/jellyfin"
        - name: DEPLOYMENT_NAME
          value: "asp-calculator"
---
apiVersion: v1
kind: Service
metadata:
  name: pod-kicker-service
spec:
  selector:
    app: pod-kicker
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8450
    nodePort: 30080
